In [2]:
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [4]:
df =  pd.read_csv("diabetes_risk.csv")

In [5]:
df.head()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
0,1,47,Female,Mumbai,26.5,Yes,Sedentary,Vegetarian,Never,Never,9.0,8,178,7.3,146,90,107.1,High,Low
1,2,53,Female,Mumbai,20.5,Yes,Moderate,Vegetarian,Never,Never,7.0,6,152,6.9,156,100,93.8,Low,Low
2,3,47,Male,Thane,31.3,No,Moderate,Non-Vegetarian,Current,Regular,7.0,7,168,6.6,150,102,113.5,Low,High
3,4,41,Male,Bengaluru,22.8,No,Sedentary,Non-Vegetarian,Never,Never,9.0,5,155,6.7,126,92,109.6,Middle,Low
4,5,57,Female,Bengaluru,16.7,No,Sedentary,Non-Vegetarian,Current,Occasional,6.5,10,188,6.7,130,90,80.8,High,Low

In [6]:
df.isna().sum()

patient_id                     0
age                            0
gender                         0
city                           0
bmi                            0
family_history_diabetes        0
physical_activity_level        0
diet_type                      0
smoking_status               472
alcohol_consumption         3788
hours_sleep_per_night          0
stress_level                   0
fasting_blood_sugar            0
hba1c_level                    0
blood_pressure_systolic        0
blood_pressure_diastolic       0
waist_circumference_cm         0
income_bracket               463
diabetes_risk                  0
dtype: int64

In [7]:
for col in ["smoking_status", "alcohol_consumption", "income_bracket"]:
    df[col] = df[col].fillna(df[col].mode()[0])

In [8]:
df.isna().sum()

patient_id                  0
age                         0
gender                      0
city                        0
bmi                         0
family_history_diabetes     0
physical_activity_level     0
diet_type                   0
smoking_status              0
alcohol_consumption         0
hours_sleep_per_night       0
stress_level                0
fasting_blood_sugar         0
hba1c_level                 0
blood_pressure_systolic     0
blood_pressure_diastolic    0
waist_circumference_cm      0
income_bracket              0
diabetes_risk               0
dtype: int64

In [9]:
df.head()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
0,1,47,Female,Mumbai,26.5,Yes,Sedentary,Vegetarian,Never,Never,9.0,8,178,7.3,146,90,107.1,High,Low
1,2,53,Female,Mumbai,20.5,Yes,Moderate,Vegetarian,Never,Never,7.0,6,152,6.9,156,100,93.8,Low,Low
2,3,47,Male,Thane,31.3,No,Moderate,Non-Vegetarian,Current,Regular,7.0,7,168,6.6,150,102,113.5,Low,High
3,4,41,Male,Bengaluru,22.8,No,Sedentary,Non-Vegetarian,Never,Never,9.0,5,155,6.7,126,92,109.6,Middle,Low
4,5,57,Female,Bengaluru,16.7,No,Sedentary,Non-Vegetarian,Current,Occasional,6.5,10,188,6.7,130,90,80.8,High,Low

In [18]:
categorical_cols = [
    "gender",
    "city",
    "family_history_diabetes",
    "physical_activity_level",
    "diet_type",
    "smoking_status",
    "alcohol_consumption",
    "income_bracket"
]

In [10]:
X = df.drop(["patient_id", "diabetes_risk"], axis=1)
y = df["diabetes_risk"]

In [11]:
X = pd.get_dummies(X, drop_first=True, dtype=int)

In [12]:
X

,age,bmi,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,gender_Male,...,physical_activity_level_Sedentary,diet_type_Pescatarian,diet_type_Vegan,diet_type_Vegetarian,smoking_status_Former,smoking_status_Never,alcohol_consumption_Occasional,alcohol_consumption_Regular,income_bracket_Low,income_bracket_Middle
0,47,26.5,9.0,8,178,7.3,146,90,107.1,0,...,1,0,0,1,0,1,0,0,0,0
1,53,20.5,7.0,6,152,6.9,156,100,93.8,0,...,0,0,0,1,0,1,0,0,1,0
2,47,31.3,7.0,7,168,6.6,150,102,113.5,1,...,0,0,0,0,0,0,0,1,1,0
3,41,22.8,9.0,5,155,6.7,126,92,109.6,1,...,1,0,0,0,0,1,0,0,0,1
4,57,16.7,6.5,10,188,6.7,130,90,80.8,0,...,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,47,37.7,6.8,7,213,8.1,150,100,141.7,1,...,1,0,0,0,0,1,0,0,0,0
14996,48,20.6,6.0,8,162,6.5,132,80,91.0,0,...,0,0,0,0,0,1,0,0,0,1
14997,34,17.9,7.0,6,137,6.5,136,90,88.8,0,...,0,0,0,1,0,1,0,0,1,0
14998,56,20.7,6.0,5,163,6.9,140,87,94.8,1,...,0,0,0,1,0,1,0,0,1,0
14999,54,34.5,7.4,2,186,7.2,150,88,130.4,1,...,0,0,0,1,0,1,0,0,0,1

In [16]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size = 0.20, stratify = y, random_state = 42,
)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler()

In [19]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
from sklearn.multiclass import OneVsRestClassifier

In [42]:
model = OneVsRestClassifier(
    LogisticRegression(max_iter = 1000,class_weight="balanced")
)

In [43]:
model

OneVsRestClassifier(estimator=LogisticRegression(class_weight='balanced',
                                                 max_iter=1000))

In [44]:
model.fit(X_train_scaled,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:451: OptimizeWarning: Unknown solver options: iprint
  opt_res = optimize.minimize(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:451: OptimizeWarning: Unknown solver options: iprint
  opt_res = optimize.minimize(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:451: OptimizeWarning: Unknown solver options: iprint
  opt_res = optimize.minimize(

OneVsRestClassifier(estimator=LogisticRegression(class_weight='balanced',
                                                 max_iter=1000))

In [45]:
y_pred = model.predict(X_test_scaled)

In [46]:
comparison = pd.DataFrame({
    "Actual": y_test,
    "Prediction": y_pred
})

In [47]:
comparison

         Actual Prediction
6245        Low        Low
9993        Low        Low
6084        Low        Low
3034   Moderate   Moderate
10818       Low        Low
...         ...        ...
4430        Low        Low
4511       High       High
1068       High       High
14655       Low        Low
4721        Low        Low

[3000 rows x 2 columns]

In [48]:
print("Accuracy :", accuracy_score(y_test,y_pred)*100)

Accuracy : 77.66666666666666

In [49]:
print("classification Report :\n", classification_report(y_test,y_pred))

classification Report :
               precision    recall  f1-score   support

        High       0.68      0.84      0.75       450
         Low       0.89      0.86      0.88      1800
    Moderate       0.57      0.54      0.55       750

    accuracy                           0.78      3000
   macro avg       0.71      0.75      0.73      3000
weighted avg       0.78      0.78      0.78      3000

In [50]:
cm = confusion_matrix(y_test, y_pred)

In [51]:
cm

array([[ 380,    2,   68],
       [  14, 1547,  239],
       [ 167,  180,  403]])